#!/usr/bin/perl -w
# Copyright 2005-2006 Tomasz Wegrzanowski
# Released under GNU General Public License, version 2 or higher

use Tawbot;

my $bot = Tawbot->new();

for my$cat(@ARGV)
{
    my @articles = $bot->articles_in_category($cat);
    print "Fixing sort key of [[Kategoria:$cat]] (", (scalar @articles),  " articles)\n";
    $bot->run(["S", "!$cat"], @articles);
}
