#!/usr/bin/perl -w
# Copyright 2005-2006 Tomasz Wegrzanowski
# Released under GNU General Public License, version 2 or higher

use Tawbot;

my $bot = Tawbot->new();

my ($title) = @ARGV;

my $form = $bot->get_edit_form($title);

print $form->value("wpTextbox1");
