#!/usr/bin/perl -w
# Copyright 2005-2006 Tomasz Wegrzanowski
# Released under GNU General Public License, version 2 or higher

use Tawbot;

my $bot = Tawbot->new();

for my $title (@ARGV)
{
    my @links = $bot->linked_to_image($title);
    for(@links)
    {
        print "$_\n";
    }
}
