#!/usr/bin/perl -w
# Copyright 2005-2006 Tomasz Wegrzanowski
# Released under GNU General Public License, version 2 or higher

use Tawbot;
package main;

my $bot = Tawbot->new();

my ($title, $summary) = @ARGV;

$/ = undef;
my $cnt = <STDIN>;

print "Trying $title ... ";
my $form = $bot->get_edit_form($title);
print "downloaded ... ";

$bot->fill_form($form, $cnt, $summary);
$bot->post($form);
print "posted.\n";
