#!/usr/bin/perl -w

$|=1;
use Tawbot;

my $bot = Tawbot->new();

while(<>)
{
    chomp;
    /^(\d+)\s+(.+)$/ or die "Parse error: $_";
    my ($num, $name) = ($1, $2);
    
    my $form = $bot->get_edit_form($name);

    my $cur = $form->value("wpTextbox1");

    my $fn = sprintf "out/%03d.dat", $num;
    open F, $fn or die "Can't open $fn: $!";
    my $new = join "", <F>;
    close F;

    print "$num $name: ";
    if ($cur =~ /^\s*$/) {
        # Empty, let's upload
        $bot->fill_form($form, $new, "A new Polish politician stub");
        $bot->post($form);
        print "posted.\n";
    } else {
        # Not empty
        print "NOT EMPTY, please integrate by hand\n";
    }
    sleep 15;
}
